# config.py - RetroDB Configuration
# ================================================
# Application constants and internal defaults.
# DO NOT edit this file — all user settings (paths, API keys) are configured
# via the web UI and stored in data/settings.json and data/scraper_settings.json.
#
# SETUP: Copy this file to config.py, then run the app and use the setup wizard.
#   cp config.example.py config.py
#
# Environment variable overrides (RETRODB_ prefix):
#   RETRODB_DB_PATH       - Database file path
#   RETRODB_HOST          - Server bind address (default: 0.0.0.0)
#   RETRODB_PORT          - Server port (default: 5000)
#   RETRODB_DEBUG         - Debug mode: "true" or "false" (default: false)
#   RETRODB_SECRET_KEY    - Flask secret key (overrides auto-generated key)

import os

# =============================================================================
# INTERNAL PATHS (not user-configurable here — use Settings page)
# =============================================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.environ.get('RETRODB_DB_PATH', os.path.join(BASE_DIR, "database", "roms.db"))
STATIC_PATH = os.path.join(BASE_DIR, "static")
IMAGE_PATH = os.path.join(STATIC_PATH, "images")

# Path defaults (empty — set via Settings page, stored in data/settings.json)
ROM_PATH = ""
ESDE_GAMELISTS_PATH = ""
ESDE_DOWNLOADED_MEDIA_PATH = ""
RPCS3_TROPHY_PATH = ""

# =============================================================================
# API KEY DEFAULTS (empty — set via Settings page, stored in data/scraper_settings.json)
# =============================================================================

THEGAMESDB_API_KEY = ""
THEGAMESDB_PUBLIC_API_KEY = ""
IGDB_CLIENT_ID = ""
IGDB_CLIENT_SECRET = ""
RAWG_API_KEY = ""
RETROACHIEVEMENTS_USERNAME = ""
RETROACHIEVEMENTS_API_KEY = ""

# AI Metadata Scraper (Gemini, OpenAI, or Claude)
AI_METADATA_PROVIDER = ""     # "gemini", "openai", or "claude"
AI_GEMINI_API_KEY = ""
AI_OPENAI_API_KEY = ""
AI_CLAUDE_API_KEY = ""

# =============================================================================
# SCRAPER TOGGLES
# =============================================================================
# Enable or disable individual scrapers
# Set to False to disable a scraper (useful if API is down or causing issues)

SCRAPER_ESDE_ENABLED = True       # ES-DE local gamelist.xml
SCRAPER_TGDB_ENABLED = True       # TheGamesDB
SCRAPER_IGDB_ENABLED = True       # IGDB
SCRAPER_RAWG_ENABLED = True       # RAWG.io

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================

# Flask server settings (overridable via RETRODB_HOST, RETRODB_PORT, RETRODB_DEBUG)
SERVER_HOST = os.environ.get('RETRODB_HOST', "0.0.0.0")
SERVER_PORT = int(os.environ.get('RETRODB_PORT', "5000"))
DEBUG_MODE = os.environ.get('RETRODB_DEBUG', "false").lower() in ('true', '1', 'yes')

# =============================================================================
# APPLICATION SETTINGS
# =============================================================================

# Application metadata
APP_NAME = "RetroDB"
APP_VERSION = "2.83.5"
APP_LAST_UPDATE = "2026-04-21"
APP_DESCRIPTION = "Retro Gaming ROM Library Manager"

# Supported image extensions for boxart/screenshots
SUPPORTED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']

# Maximum results to show in search
MAX_SEARCH_RESULTS = 10

# =============================================================================
# SYSTEM NAME MAPPING
# =============================================================================
# Maps ES-DE folder names to full system names

SYSTEM_NAME_MAP = {
    # Nintendo
    "nes": "Nintendo Entertainment System",
    "famicom": "Nintendo Famicom",
    "fds": "Famicom Disk System",
    "snes": "Super Nintendo Entertainment System",
    "sfc": "Super Famicom",
    "n64": "Nintendo 64",
    "n64dd": "Nintendo 64DD",
    "gb": "Game Boy",
    "gbc": "Game Boy Color",
    "gba": "Game Boy Advance",
    "nds": "Nintendo DS",
    "n3ds": "Nintendo 3DS",
    "gc": "Nintendo GameCube",
    "wii": "Nintendo Wii",
    "wiiu": "Nintendo Wii U",
    "switch": "Nintendo Switch",
    "virtualboy": "Virtual Boy",
    "pokemini": "Pokemon Mini",
    "satellaview": "Satellaview",
    "sufami": "SuFami Turbo",
    "sgb": "Super Game Boy",
    "gameandwatch": "Game & Watch",

    # Sony
    "psx": "Sony PlayStation",
    "ps2": "Sony PlayStation 2",
    "ps3": "Sony PlayStation 3",
    "ps4": "Sony PlayStation 4",
    "ps5": "Sony PlayStation 5",
    "psp": "Sony PlayStation Portable",
    "psvita": "Sony PlayStation Vita",

    # Sega
    "genesis": "Sega Genesis",
    "megadrive": "Sega Mega Drive",
    "megadrivejp": "Sega Mega Drive (Japan)",
    "mastersystem": "Sega Master System",
    "segacd": "Sega CD",
    "sega32x": "Sega 32X",
    "sega32xjp": "Sega 32X (Japan)",
    "sega32xna": "Sega 32X (North America)",
    "saturn": "Sega Saturn",
    "saturnjp": "Sega Saturn (Japan)",
    "dreamcast": "Sega Dreamcast",
    "gamegear": "Sega Game Gear",
    "sg-1000": "Sega SG-1000",
    "sc-3000": "Sega SC-3000",
    "model2": "Sega Model 2",
    "model3": "Sega Model 3",
    "naomi": "Sega Naomi",
    "naomi2": "Sega Naomi 2",
    "stv": "Sega Titan Video",

    # Microsoft
    "xbox": "Microsoft Xbox",
    "xbox360": "Microsoft Xbox 360",
    "xboxone": "Microsoft Xbox One",

    # Atari
    "atari2600": "Atari 2600",
    "atari5200": "Atari 5200",
    "atari7800": "Atari 7800",
    "atari800": "Atari 800",
    "atarist": "Atari ST",
    "atarixe": "Atari XE",
    "atarijaguar": "Atari Jaguar",
    "atarijaguarcd": "Atari Jaguar CD",
    "atarilynx": "Atari Lynx",

    # NEC
    "pcengine": "PC Engine",
    "pcenginecd": "PC Engine CD",
    "supergrafx": "PC Engine SuperGrafx",
    "tg16": "TurboGrafx-16",
    "tg-cd": "TurboGrafx-CD",
    "pcfx": "PC-FX",

    # SNK
    "neogeo": "SNK Neo Geo",
    "neogeocd": "SNK Neo Geo CD",
    "neogeocdjp": "SNK Neo Geo CD (Japan)",
    "ngp": "Neo Geo Pocket",
    "ngpc": "Neo Geo Pocket Color",

    # Arcade
    "arcade": "Arcade",
    "mame": "MAME",
    "fbneo": "FinalBurn Neo",
    "daphne": "Daphne",
    "consolearcade": "Console Arcade",
    "pcarcade": "PC Arcade",

    # Computers
    "dos": "MS-DOS",
    "pc": "IBM PC",
    "windows": "Microsoft Windows",
    "windows3x": "Windows 3.x",
    "windows9x": "Windows 9x",
    "macintosh": "Apple Macintosh",
    "apple2": "Apple II",
    "apple2gs": "Apple IIGS",
    "amiga": "Commodore Amiga",
    "amigacd32": "Commodore Amiga CD32",
    "cdtv": "Commodore CDTV",
    "c64": "Commodore 64",
    "vic20": "Commodore VIC-20",
    "plus4": "Commodore Plus/4",
    "amstradcpc": "Amstrad CPC",
    "msx": "MSX",
    "msx1": "MSX",
    "msx2": "MSX2",
    "msxturbor": "MSX Turbo R",
    "zxspectrum": "ZX Spectrum",
    "zx81": "Sinclair ZX81",
    "zxnext": "ZX Spectrum Next",
    "electron": "Acorn Electron",
    "archimedes": "Acorn Archimedes",
    "bbcmicro": "BBC Micro",
    "oric": "Oric",
    "coco": "TRS-80 Color Computer",
    "trs-80": "TRS-80",
    "ti99": "Texas Instruments TI-99/4A",
    "moto": "Thomson MO/TO",
    "to8": "Thomson TO8",
    "fm7": "Fujitsu FM-7",
    "x1": "Sharp X1",
    "x68000": "Sharp X68000",
    "pc88": "NEC PC-8801",
    "pc98": "NEC PC-9801",

    # Other Consoles
    "3do": "3DO Interactive Multiplayer",
    "colecovision": "ColecoVision",
    "intellivision": "Mattel Intellivision",
    "vectrex": "Vectrex",
    "channelf": "Fairchild Channel F",
    "odyssey2": "Magnavox Odyssey 2",
    "videopac": "Philips Videopac",
    "cdimono1": "Philips CD-i",
    "astrocade": "Bally Astrocade",
    "astrocde": "Bally Astrocade",
    "wonderswan": "Bandai WonderSwan",
    "wonderswancolor": "Bandai WonderSwan Color",
    "ngage": "Nokia N-Gage",
    "palm": "Palm OS",
    "gx4000": "Amstrad GX4000",
    "supervision": "Watara Supervision",
    "gamate": "Bit Corporation Gamate",
    "gamecom": "Tiger Game.com",
    "supracan": "Funtech Super A'Can",
    "crvision": "VTech CreatiVision",
    "scv": "Epoch Super Cassette Vision",
    "arcadia": "Emerson Arcadia 2001",
    "multivision": "Othello Multivision",
    "vsmile": "VTech V.Smile",

    # GamePark Handhelds
    "gp32": "GamePark GP32",

    # Modern/Other
    "lutro": "Lutro",
    "tic80": "TIC-80",
    "arduboy": "Arduboy",
    "uzebox": "Uzebox",
    "vircon32": "Vircon32",
    "ports": "Ports",
    "zmachine": "Z-Machine",
}

# =============================================================================
# THEGAMESDB SYSTEM ID MAPPING
# =============================================================================
# Maps system names to TheGamesDB platform IDs

TGDB_SYSTEM_MAP = {
    # Nintendo
    "nintendo entertainment system": 7,
    "nes": 7,
    "famicom": 7,
    "fds": 4936,
    "super nintendo entertainment system": 6,
    "super nintendo": 6,
    "snes": 6,
    "sfc": 6,
    "nintendo 64": 3,
    "n64": 3,
    "game boy": 4,
    "gb": 4,
    "game boy color": 41,
    "gbc": 41,
    "game boy advance": 5,
    "gba": 5,
    "nintendo ds": 8,
    "nds": 8,
    "nintendo 3ds": 4912,
    "n3ds": 4912,
    "nintendo gamecube": 2,
    "gamecube": 2,
    "gc": 2,
    "nintendo wii": 9,
    "wii": 9,
    "nintendo wii u": 38,
    "wiiu": 38,
    "nintendo switch": 4971,
    "switch": 4971,
    "virtual boy": 4918,
    "virtualboy": 4918,

    # Sony
    "sony playstation": 10,
    "playstation": 10,
    "psx": 10,
    "ps1": 10,
    "sony playstation 2": 11,
    "playstation 2": 11,
    "ps2": 11,
    "sony playstation 3": 12,
    "playstation 3": 12,
    "ps3": 12,
    "sony playstation 4": 4919,
    "playstation 4": 4919,
    "ps4": 4919,
    "sony playstation 5": 4980,
    "playstation 5": 4980,
    "ps5": 4980,
    "sony playstation portable": 13,
    "playstation portable": 13,
    "psp": 13,
    "sony playstation vita": 39,
    "playstation vita": 39,
    "psvita": 39,

    # Sega
    "sega genesis": 18,
    "genesis": 18,
    "sega mega drive": 36,
    "megadrive": 36,
    "sega master system": 35,
    "mastersystem": 35,
    "sega cd": 21,
    "segacd": 21,
    "sega 32x": 33,
    "sega32x": 33,
    "sega saturn": 17,
    "saturn": 17,
    "sega dreamcast": 16,
    "dreamcast": 16,
    "sega game gear": 20,
    "gamegear": 20,
    "sega sg-1000": 4949,
    "sg-1000": 4949,

    # Microsoft
    "microsoft xbox": 14,
    "xbox": 14,
    "microsoft xbox 360": 15,
    "xbox360": 15,
    "xbox 360": 15,
    "microsoft xbox one": 4920,
    "xbox one": 4920,
    "xboxone": 4920,

    # Atari
    "atari 2600": 22,
    "atari2600": 22,
    "atari 5200": 26,
    "atari5200": 26,
    "atari 7800": 27,
    "atari7800": 27,
    "atari jaguar": 28,
    "atarijaguar": 28,
    "atari lynx": 29,
    "atarilynx": 29,
    "atari st": 4937,
    "atarist": 4937,

    # NEC
    "pc engine": 34,
    "pcengine": 34,
    "turbografx-16": 34,
    "tg16": 34,
    "pc engine cd": 4955,
    "supergrafx": 4950,
    "pc-fx": 4930,
    "pcfx": 4930,

    # SNK
    "neo geo": 24,
    "neogeo": 24,
    "neo geo cd": 4956,
    "neogeocd": 4956,
    "neo geo pocket": 4922,
    "ngp": 4922,
    "neo geo pocket color": 4923,
    "ngpc": 4923,

    # Arcade
    "arcade": 23,
    "mame": 23,

    # Computers
    "ms-dos": 1,
    "dos": 1,
    "commodore 64": 40,
    "c64": 40,
    "amiga": 4911,
    "amstrad cpc": 4914,
    "amstradcpc": 4914,
    "msx": 4929,
    "zx spectrum": 4913,
    "zxspectrum": 4913,

    # Other
    "3do interactive multiplayer": 25,
    "3do": 25,
    "colecovision": 31,
    "intellivision": 32,
    "vectrex": 4939,
    "wonderswan": 4925,
    "wonderswan color": 4926,
    "wonderswancolor": 4926,
}

# =============================================================================
# IGDB PLATFORM ID MAPPING
# =============================================================================
# Maps system names to IGDB platform IDs

IGDB_PLATFORM_MAP = {
    # Nintendo - short names
    "nes": 18,
    "snes": 19,
    "n64": 4,
    "gb": 33,
    "gbc": 22,
    "gba": 24,
    "nds": 20,
    "n3ds": 37,
    "gc": 21,
    "wii": 5,
    "wiiu": 41,
    "switch": 130,
    "virtualboy": 87,
    # Nintendo - full names
    "nintendo entertainment system": 18,
    "super nintendo entertainment system": 19,
    "nintendo 64": 4,
    "game boy": 33,
    "game boy color": 22,
    "game boy advance": 24,
    "nintendo ds": 20,
    "nintendo 3ds": 37,
    "nintendo gamecube": 21,
    "nintendo wii": 5,
    "nintendo wii u": 41,
    "nintendo switch": 130,
    "virtual boy": 87,

    # Sony - short names
    "psx": 7,
    "ps2": 8,
    "ps3": 9,
    "ps4": 48,
    "ps5": 167,
    "psp": 38,
    "psvita": 46,
    # Sony - full names
    "sony playstation": 7,
    "playstation": 7,
    "sony playstation 2": 8,
    "playstation 2": 8,
    "sony playstation 3": 9,
    "playstation 3": 9,
    "sony playstation 4": 48,
    "playstation 4": 48,
    "sony playstation 5": 167,
    "playstation 5": 167,
    "sony playstation portable": 38,
    "playstation portable": 38,
    "sony playstation vita": 46,
    "playstation vita": 46,

    # Sega - short names
    "genesis": 29,
    "mastersystem": 64,
    "segacd": 78,
    "sega32x": 30,
    "saturn": 32,
    "dreamcast": 23,
    "gamegear": 35,
    # Sega - full names
    "sega genesis": 29,
    "sega mega drive": 29,
    "sega master system": 64,
    "sega cd": 78,
    "sega 32x": 30,
    "sega saturn": 32,
    "sega dreamcast": 23,
    "sega game gear": 35,

    # Microsoft
    "xbox": 11,
    "xbox360": 12,
    "xboxone": 49,
    "xbox 360": 12,
    "xbox one": 49,
    "microsoft xbox": 11,
    "microsoft xbox 360": 12,
    "microsoft xbox one": 49,

    # Other
    "atari2600": 59,
    "atari5200": 66,
    "atari7800": 60,
    "atarijaguar": 62,
    "atarilynx": 61,
    "atari 2600": 59,
    "atari 5200": 66,
    "atari 7800": 60,
    "atari jaguar": 62,
    "atari lynx": 61,
    "pcengine": 86,
    "tg16": 86,
    "pc engine": 86,
    "turbografx-16": 86,
    "neogeo": 80,
    "neo geo": 80,
    "ngp": 119,
    "ngpc": 120,
    "neo geo pocket": 119,
    "neo geo pocket color": 120,
    "arcade": 52,
    "dos": 13,
    "c64": 15,
    "commodore 64": 15,
    "amiga": 16,
    "3do": 50,
    "colecovision": 68,
    "intellivision": 67,
    "wonderswan": 57,
    "wonderswancolor": 123,
    "wonder swan": 57,
    "wonder swan color": 123,
}

# =============================================================================
# GENRE ID MAPPING FOR THEGAMESDB
# =============================================================================

TGDB_GENRE_MAP = {
    1: "Action",
    2: "Adventure",
    3: "Arcade",
    4: "Beat 'em Up",
    5: "Board Game",
    6: "Card Game",
    7: "Casino",
    8: "Fighting",
    9: "FPS",
    10: "Flight Simulator",
    11: "Life Simulation",
    12: "Music",
    13: "Party",
    14: "Platformer",
    15: "Puzzle",
    16: "Racing",
    17: "Real-Time Strategy",
    18: "RPG",
    19: "Sandbox",
    20: "Shoot 'em Up",
    21: "Simulation",
    22: "Sports",
    23: "Strategy",
    24: "Survival",
    25: "Tactical RPG",
    26: "Turn-Based Strategy",
    27: "Vehicular Combat",
}

# =============================================================================
# ESRB RATING MAPPING
# =============================================================================

ESRB_RATINGS = {
    "EC": {"name": "Early Childhood", "age": "3+", "color": "#00C853"},
    "E": {"name": "Everyone", "age": "6+", "color": "#00C853"},
    "E10+": {"name": "Everyone 10+", "age": "10+", "color": "#76FF03"},
    "T": {"name": "Teen", "age": "13+", "color": "#FFD600"},
    "M": {"name": "Mature 17+", "age": "17+", "color": "#FF6D00"},
    "AO": {"name": "Adults Only 18+", "age": "18+", "color": "#D50000"},
    "RP": {"name": "Rating Pending", "age": "N/A", "color": "#9E9E9E"},
}

# =============================================================================
# PEGI RATING MAPPING
# =============================================================================

PEGI_RATINGS = {
    "3": {"name": "PEGI 3", "age": "3+", "color": "#00C853"},
    "7": {"name": "PEGI 7", "age": "7+", "color": "#76FF03"},
    "12": {"name": "PEGI 12", "age": "12+", "color": "#FFD600"},
    "16": {"name": "PEGI 16", "age": "16+", "color": "#FF6D00"},
    "18": {"name": "PEGI 18", "age": "18+", "color": "#D50000"},
}

# =============================================================================
# SYSTEM SPECIFICATIONS
# =============================================================================
# Technical specifications for gaming systems

SYSTEM_SPECS = {
    # Nintendo
    "nes": {
        "manufacturer": "Nintendo",
        "released": "1983 (JP), 1985 (NA)",
        "cpu": "Ricoh 2A03 @ 1.79 MHz",
        "ram": "2 KB",
        "vram": "2 KB",
        "resolution": "256x240",
        "colors": "54 colors (25 on screen)",
        "sound": "5 channels (2 pulse, 1 triangle, 1 noise, 1 DPCM)",
        "media": "Cartridge",
        "generation": "3rd Generation",
    },
    "snes": {
        "manufacturer": "Nintendo",
        "released": "1990 (JP), 1991 (NA)",
        "cpu": "Ricoh 5A22 @ 3.58 MHz",
        "ram": "128 KB",
        "vram": "64 KB",
        "resolution": "256x224 to 512x448",
        "colors": "32,768 colors (256 on screen)",
        "sound": "Sony SPC700 (8 channels, 16-bit)",
        "media": "Cartridge",
        "generation": "4th Generation",
    },
    "n64": {
        "manufacturer": "Nintendo",
        "released": "1996",
        "cpu": "NEC VR4300 @ 93.75 MHz",
        "gpu": "Reality Coprocessor @ 62.5 MHz",
        "ram": "4 MB (expandable to 8 MB)",
        "resolution": "256x224 to 640x480",
        "colors": "16.7 million",
        "sound": "16-bit stereo",
        "media": "Cartridge",
        "generation": "5th Generation",
    },
    "gc": {
        "manufacturer": "Nintendo",
        "released": "2001",
        "cpu": "IBM PowerPC Gekko @ 485 MHz",
        "gpu": "ATI Flipper @ 162 MHz",
        "ram": "24 MB + 16 MB A-RAM",
        "resolution": "Up to 480p",
        "colors": "16.7 million",
        "sound": "Dolby Pro Logic II",
        "media": "Mini DVD",
        "generation": "6th Generation",
    },
    "wii": {
        "manufacturer": "Nintendo",
        "released": "2006",
        "cpu": "IBM Broadway @ 729 MHz",
        "gpu": "ATI Hollywood @ 243 MHz",
        "ram": "88 MB",
        "resolution": "Up to 480p",
        "colors": "16.7 million",
        "sound": "Dolby Pro Logic II",
        "media": "Wii Optical Disc, DVD",
        "generation": "7th Generation",
    },
    "wiiu": {
        "manufacturer": "Nintendo",
        "released": "2012",
        "cpu": "IBM Espresso (PowerPC tri-core) @ 1.24 GHz",
        "gpu": "AMD Radeon Latte @ 550 MHz",
        "ram": "2 GB DDR3 (1 GB for games)",
        "resolution": "Up to 1080p",
        "colors": "16.7 million",
        "sound": "6-channel PCM linear output",
        "media": "Wii U Optical Disc, Wii Optical Disc",
        "storage": "8 GB (Basic), 32 GB (Deluxe)",
        "generation": "8th Generation",
    },
    "gb": {
        "manufacturer": "Nintendo",
        "released": "1989",
        "cpu": "Sharp LR35902 @ 4.19 MHz",
        "ram": "8 KB",
        "vram": "8 KB",
        "resolution": "160x144",
        "colors": "4 shades of green",
        "sound": "4 channels",
        "media": "Cartridge",
        "generation": "4th Generation (Handheld)",
    },
    "gbc": {
        "manufacturer": "Nintendo",
        "released": "1998",
        "cpu": "Sharp LR35902 @ 8.39 MHz",
        "ram": "32 KB",
        "vram": "16 KB",
        "resolution": "160x144",
        "colors": "32,768 (56 on screen)",
        "sound": "4 channels",
        "media": "Cartridge",
        "generation": "5th Generation (Handheld)",
    },
    "gba": {
        "manufacturer": "Nintendo",
        "released": "2001",
        "cpu": "ARM7TDMI @ 16.78 MHz",
        "ram": "32 KB + 256 KB",
        "vram": "96 KB",
        "resolution": "240x160",
        "colors": "32,768 (511 on screen)",
        "sound": "6 channels (4 legacy + 2 PCM)",
        "media": "Cartridge",
        "generation": "6th Generation (Handheld)",
    },
    "nds": {
        "manufacturer": "Nintendo",
        "released": "2004",
        "cpu": "ARM9 @ 67 MHz + ARM7 @ 33 MHz",
        "ram": "4 MB",
        "vram": "656 KB",
        "resolution": "256x192 (x2 screens)",
        "colors": "262,144",
        "sound": "16 channels",
        "media": "DS Game Card",
        "generation": "7th Generation (Handheld)",
    },

    # Sony
    "psx": {
        "manufacturer": "Sony",
        "released": "1994 (JP), 1995 (NA/EU)",
        "cpu": "R3000A @ 33.87 MHz",
        "gpu": "Custom @ 53.2 MHz",
        "ram": "2 MB + 1 MB VRAM",
        "resolution": "256x224 to 640x480",
        "colors": "16.7 million",
        "sound": "24 channels, 16-bit",
        "media": "CD-ROM",
        "generation": "5th Generation",
    },
    "ps2": {
        "manufacturer": "Sony",
        "released": "2000",
        "cpu": "Emotion Engine @ 294.912 MHz",
        "gpu": "Graphics Synthesizer @ 147.456 MHz",
        "ram": "32 MB RDRAM + 4 MB VRAM",
        "resolution": "Up to 1080i",
        "colors": "16.7 million",
        "sound": "48 channels, SPU2",
        "media": "DVD-ROM, CD-ROM",
        "generation": "6th Generation",
    },
    "ps3": {
        "manufacturer": "Sony",
        "released": "2006",
        "cpu": "Cell Broadband Engine @ 3.2 GHz",
        "gpu": "RSX Reality Synthesizer @ 550 MHz",
        "ram": "256 MB XDR + 256 MB GDDR3",
        "resolution": "Up to 1080p",
        "colors": "16.7 million",
        "sound": "Dolby TrueHD, DTS-HD",
        "media": "Blu-ray, DVD, CD",
        "generation": "7th Generation",
    },
    "ps4": {
        "manufacturer": "Sony",
        "released": "2013",
        "cpu": "AMD Jaguar 8-core @ 1.6 GHz",
        "gpu": "AMD Radeon @ 800 MHz (1.84 TFLOPS)",
        "ram": "8 GB GDDR5",
        "resolution": "Up to 1080p (4K video playback)",
        "colors": "16.7 million",
        "sound": "Dolby TrueHD, DTS-HD Master Audio",
        "media": "Blu-ray, DVD",
        "storage": "500 GB / 1 TB HDD",
        "generation": "8th Generation",
    },
    "ps5": {
        "manufacturer": "Sony",
        "released": "2020",
        "cpu": "AMD Zen 2 8-core @ 3.5 GHz (variable)",
        "gpu": "AMD RDNA 2 @ 2.23 GHz (10.28 TFLOPS)",
        "ram": "16 GB GDDR6 (unified)",
        "resolution": "Up to 4K @ 120Hz, 8K supported",
        "colors": "16.7 million",
        "sound": "Tempest 3D AudioTech, Dolby Atmos",
        "media": "Ultra HD Blu-ray, Blu-ray, DVD",
        "storage": "825 GB custom SSD (667 GB usable)",
        "generation": "9th Generation",
    },
    "psp": {
        "manufacturer": "Sony",
        "released": "2004 (JP), 2005 (NA/EU)",
        "cpu": "MIPS R4000 @ 333 MHz",
        "gpu": "Custom @ 166 MHz",
        "ram": "32 MB (64 MB on later models)",
        "resolution": "480x272",
        "colors": "16.7 million",
        "sound": "Stereo speakers",
        "media": "UMD",
        "generation": "7th Generation (Handheld)",
    },

    # Sega
    "mastersystem": {
        "manufacturer": "Sega",
        "released": "1985 (JP), 1986 (NA)",
        "cpu": "Zilog Z80 @ 3.58 MHz",
        "ram": "8 KB",
        "vram": "16 KB",
        "resolution": "256x192",
        "colors": "64 (32 on screen)",
        "sound": "4 channels (3 tone + 1 noise)",
        "media": "Cartridge, Sega Card",
        "generation": "3rd Generation",
    },
    "megadrive": {
        "manufacturer": "Sega",
        "released": "1988 (JP), 1989 (NA)",
        "cpu": "Motorola 68000 @ 7.6 MHz + Z80 @ 3.58 MHz",
        "ram": "64 KB + 8 KB",
        "vram": "64 KB",
        "resolution": "320x224 to 320x448",
        "colors": "512 (61 on screen)",
        "sound": "Yamaha YM2612 + SN76489",
        "media": "Cartridge",
        "generation": "4th Generation",
    },
    "genesis": {
        "manufacturer": "Sega",
        "released": "1989 (NA)",
        "cpu": "Motorola 68000 @ 7.6 MHz + Z80 @ 3.58 MHz",
        "ram": "64 KB + 8 KB",
        "vram": "64 KB",
        "resolution": "320x224 to 320x448",
        "colors": "512 (61 on screen)",
        "sound": "Yamaha YM2612 + SN76489",
        "media": "Cartridge",
        "generation": "4th Generation",
    },
    "segacd": {
        "manufacturer": "Sega",
        "released": "1991 (JP), 1992 (NA)",
        "cpu": "68000 @ 12.5 MHz (+ Genesis CPU)",
        "ram": "768 KB",
        "vram": "256 KB",
        "resolution": "320x224",
        "colors": "512",
        "sound": "CD-DA + PCM",
        "media": "CD-ROM",
        "generation": "4th Generation",
    },
    "sega32x": {
        "manufacturer": "Sega",
        "released": "1994",
        "cpu": "2x Hitachi SH-2 @ 23 MHz",
        "ram": "256 KB + 256 KB VRAM",
        "vram": "256 KB",
        "resolution": "320x224",
        "colors": "32,768",
        "sound": "PWM",
        "media": "Cartridge",
        "generation": "4th Generation",
    },
    "saturn": {
        "manufacturer": "Sega",
        "released": "1994 (JP), 1995 (NA)",
        "cpu": "2x Hitachi SH-2 @ 28.6 MHz",
        "gpu": "2x VDP",
        "ram": "2 MB + 1.5 MB VRAM",
        "resolution": "320x224 to 704x480",
        "colors": "16.7 million",
        "sound": "Yamaha SCSP (32 channels)",
        "media": "CD-ROM",
        "generation": "5th Generation",
    },
    "dreamcast": {
        "manufacturer": "Sega",
        "released": "1998 (JP), 1999 (NA)",
        "cpu": "Hitachi SH-4 @ 200 MHz",
        "gpu": "PowerVR2 @ 100 MHz",
        "ram": "16 MB + 8 MB VRAM",
        "resolution": "Up to 480p",
        "colors": "16.7 million",
        "sound": "Yamaha AICA (64 channels)",
        "media": "GD-ROM",
        "generation": "6th Generation",
    },
    "gamegear": {
        "manufacturer": "Sega",
        "released": "1990 (JP), 1991 (NA)",
        "cpu": "Zilog Z80 @ 3.58 MHz",
        "ram": "8 KB",
        "vram": "16 KB",
        "resolution": "160x144",
        "colors": "4,096 (32 on screen)",
        "sound": "4 channels",
        "media": "Cartridge",
        "generation": "4th Generation (Handheld)",
    },

    # Atari
    "atari2600": {
        "manufacturer": "Atari",
        "released": "1977",
        "cpu": "MOS 6507 @ 1.19 MHz",
        "ram": "128 bytes",
        "vram": "N/A (TIA)",
        "resolution": "160x192",
        "colors": "128 (4 on screen)",
        "sound": "2 channels",
        "media": "Cartridge",
        "generation": "2nd Generation",
    },
    "atari5200": {
        "manufacturer": "Atari",
        "released": "1982",
        "cpu": "MOS 6502C @ 1.79 MHz",
        "ram": "16 KB",
        "resolution": "320x192",
        "colors": "256 (16 on screen)",
        "sound": "4 channels",
        "media": "Cartridge",
        "generation": "2nd Generation",
    },
    "atari7800": {
        "manufacturer": "Atari",
        "released": "1986",
        "cpu": "6502C @ 1.79 MHz",
        "ram": "4 KB",
        "vram": "N/A",
        "resolution": "320x240",
        "colors": "256 (25 on screen)",
        "sound": "2 channels (TIA)",
        "media": "Cartridge",
        "generation": "3rd Generation",
    },
    "atarilynx": {
        "manufacturer": "Atari",
        "released": "1989",
        "cpu": "WDC 65SC02 @ 4 MHz",
        "ram": "64 KB",
        "resolution": "160x102",
        "colors": "4,096 (16 on screen)",
        "sound": "4 channels",
        "media": "Cartridge",
        "generation": "4th Generation (Handheld)",
    },
    "atarijaguar": {
        "manufacturer": "Atari",
        "released": "1993",
        "cpu": "Motorola 68000 @ 13.3 MHz + 2x 32-bit RISC",
        "ram": "2 MB",
        "resolution": "Up to 800x576",
        "colors": "16.7 million",
        "sound": "Stereo 16-bit",
        "media": "Cartridge",
        "generation": "5th Generation",
    },
    "atari800": {
        "manufacturer": "Atari",
        "released": "1979",
        "cpu": "MOS 6502B @ 1.79 MHz",
        "ram": "8 KB (expandable to 48 KB)",
        "vram": "Shared",
        "resolution": "320x192",
        "colors": "256 (via GTIA)",
        "sound": "POKEY (4 channels)",
        "media": "Cartridge, Floppy, Cassette",
        "generation": "8-bit Computer",
    },
    "atarist": {
        "manufacturer": "Atari",
        "released": "1985",
        "cpu": "Motorola 68000 @ 8 MHz",
        "ram": "512 KB to 4 MB",
        "vram": "32 KB",
        "resolution": "640x400 (mono), 320x200 (color)",
        "colors": "512 (16 on screen)",
        "sound": "Yamaha YM2149 (3 channels)",
        "media": "Floppy Disk",
        "generation": "16-bit Computer",
    },

    # SNK
    "neogeo": {
        "manufacturer": "SNK",
        "released": "1990",
        "cpu": "Motorola 68000 @ 12 MHz + Zilog Z80 @ 4 MHz",
        "ram": "64 KB + 2 KB + 68 KB VRAM",
        "resolution": "320x224",
        "colors": "65,536 (4,096 on screen)",
        "sound": "Yamaha YM2610 (15 channels)",
        "media": "Cartridge",
        "generation": "4th Generation",
    },
    "neogeocd": {
        "manufacturer": "SNK",
        "released": "1994",
        "cpu": "Motorola 68000 @ 12 MHz + Z80 @ 4 MHz",
        "ram": "7 MB",
        "resolution": "320x224",
        "colors": "65,536",
        "sound": "Yamaha YM2610",
        "media": "CD-ROM",
        "generation": "5th Generation",
    },

    # Other
    "3do": {
        "manufacturer": "The 3DO Company",
        "released": "1993",
        "cpu": "ARM60 @ 12.5 MHz",
        "gpu": "2x Custom",
        "ram": "2 MB + 1 MB VRAM",
        "resolution": "640x480",
        "colors": "16.7 million",
        "sound": "16-bit stereo",
        "media": "CD-ROM",
        "generation": "5th Generation",
    },
    "colecovision": {
        "manufacturer": "Coleco",
        "released": "1982",
        "cpu": "Zilog Z80 @ 3.58 MHz",
        "ram": "1 KB",
        "vram": "16 KB",
        "resolution": "256x192",
        "colors": "16",
        "sound": "3 channels + 1 noise",
        "media": "Cartridge",
        "generation": "2nd Generation",
    },
    "intellivision": {
        "manufacturer": "Mattel",
        "released": "1979",
        "cpu": "GI CP1610 @ 895 kHz",
        "ram": "1.5 KB",
        "resolution": "159x96",
        "colors": "16",
        "sound": "3 channels",
        "media": "Cartridge",
        "generation": "2nd Generation",
    },
    "cdimono1": {
        "manufacturer": "Philips",
        "released": "1991",
        "cpu": "Philips SCC68070 @ 15.5 MHz",
        "gpu": "SCC66470 / MCD212",
        "ram": "1 MB (2.5 MB with DVC)",
        "resolution": "384x280 to 768x560",
        "colors": "16.7 million",
        "sound": "16-bit stereo",
        "media": "CD-ROM",
        "generation": "4th Generation",
    },
    "gp32": {
        "manufacturer": "GamePark",
        "released": "2001",
        "cpu": "ARM920T @ 133 MHz",
        "ram": "8 MB SDRAM",
        "resolution": "320x240",
        "colors": "65,536",
        "sound": "16-bit stereo, 44.1 kHz",
        "media": "SmartMedia Card",
        "generation": "6th Generation (Handheld)",
    },
    "astrocade": {
        "manufacturer": "Bally",
        "released": "1978",
        "cpu": "Zilog Z80 @ 1.789 MHz",
        "ram": "4 KB",
        "vram": "Shared",
        "resolution": "160x102",
        "colors": "256 (8 on screen)",
        "sound": "3 channels + noise",
        "media": "Cartridge",
        "generation": "2nd Generation",
    },
    "astrocde": {
        "manufacturer": "Bally",
        "released": "1978",
        "cpu": "Zilog Z80 @ 1.789 MHz",
        "ram": "4 KB",
        "vram": "Shared",
        "resolution": "160x102",
        "colors": "256 (8 on screen)",
        "sound": "3 channels + noise",
        "media": "Cartridge",
        "generation": "2nd Generation",
    },

    # Computers
    "c64": {
        "manufacturer": "Commodore",
        "released": "1982",
        "cpu": "MOS 6510 @ 1.02 MHz",
        "ram": "64 KB",
        "vram": "Shared",
        "resolution": "320x200",
        "colors": "16",
        "sound": "SID 6581 (3 channels)",
        "media": "Cartridge, Floppy, Tape",
        "generation": "8-bit Computer",
    },
    "amiga": {
        "manufacturer": "Commodore",
        "released": "1985",
        "cpu": "Motorola 68000 @ 7.14 MHz",
        "ram": "256 KB to 8 MB",
        "resolution": "Up to 640x512",
        "colors": "4,096 (HAM: 4,096)",
        "sound": "Paula (4 channels, 8-bit)",
        "media": "Floppy Disk",
        "generation": "16-bit Computer",
    },
    "amstradcpc": {
        "manufacturer": "Amstrad",
        "released": "1984",
        "cpu": "Zilog Z80 @ 4 MHz",
        "ram": "64 KB / 128 KB",
        "resolution": "640x200",
        "colors": "27 (16 on screen)",
        "sound": "AY-3-8912 (3 channels)",
        "media": "Cassette, Floppy",
        "generation": "8-bit Computer",
    },
    "zxspectrum": {
        "manufacturer": "Sinclair",
        "released": "1982",
        "cpu": "Zilog Z80 @ 3.5 MHz",
        "ram": "16 KB / 48 KB / 128 KB",
        "resolution": "256x192",
        "colors": "15",
        "sound": "Beeper (later: AY-3-8912)",
        "media": "Cassette",
        "generation": "8-bit Computer",
    },
    "msx": {
        "manufacturer": "Various (Microsoft Standard)",
        "released": "1983",
        "cpu": "Zilog Z80 @ 3.58 MHz",
        "ram": "8 KB to 64 KB",
        "resolution": "256x192",
        "colors": "16",
        "sound": "AY-3-8910 (3 channels)",
        "media": "Cartridge, Floppy, Cassette",
        "generation": "8-bit Computer",
    },
    "dos": {
        "manufacturer": "IBM / Microsoft",
        "released": "1981",
        "cpu": "Intel 8088 and above",
        "ram": "Variable",
        "resolution": "Various (CGA to VGA)",
        "colors": "Various",
        "sound": "PC Speaker, Sound Cards",
        "media": "Floppy, Hard Drive, CD-ROM",
        "generation": "PC",
    },
    "arcade": {
        "manufacturer": "Various",
        "released": "1970s-Present",
        "cpu": "Various",
        "ram": "Various",
        "resolution": "Various",
        "colors": "Various",
        "sound": "Various",
        "media": "ROM Boards",
        "generation": "Arcade",
    },
    "mame": {
        "manufacturer": "Various",
        "released": "1970s-Present",
        "cpu": "Various",
        "ram": "Various",
        "resolution": "Various",
        "colors": "Various",
        "sound": "Various",
        "media": "ROM Boards",
        "generation": "Arcade",
    },

    # Microsoft
    "xbox360": {
        "manufacturer": "Microsoft",
        "released": "2005",
        "cpu": "IBM Xenon (PowerPC tri-core) @ 3.2 GHz",
        "gpu": "ATI Xenos @ 500 MHz (240 GFLOPS)",
        "ram": "512 MB GDDR3 (unified)",
        "resolution": "Up to 1080p",
        "colors": "16.7 million",
        "sound": "320 independent decompression channels, Dolby Digital 5.1",
        "media": "DVD-DL, CD, Digital Download",
        "storage": "4 GB / 250 GB / 320 GB HDD",
        "generation": "7th Generation",
    },
    "xboxone": {
        "manufacturer": "Microsoft",
        "released": "2013",
        "cpu": "AMD Jaguar 8-core @ 1.75 GHz",
        "gpu": "AMD Radeon @ 853 MHz (1.31 TFLOPS)",
        "ram": "8 GB DDR3 + 32 MB eSRAM",
        "resolution": "Up to 1080p (4K video playback)",
        "colors": "16.7 million",
        "sound": "Dolby Atmos, DTS:X, Spatial Sound",
        "media": "Blu-ray, DVD, Digital Download",
        "storage": "500 GB / 1 TB HDD",
        "generation": "8th Generation",
    },
}
