# =============================================================================
# Migration 001 — baseline schema
# =============================================================================
# Snapshot of the schema as it stood when versioned migrations were introduced
# (v2.91.0). Idempotent so legacy installs whose schema was built up by the
# pre-migration `_migrate_*` pattern can advance to user_version=1 without
# duplicating work or erroring on already-existing objects.
#
# DO NOT edit this file to change schema for new installs — write a new
# migration file (NNN_description.py) instead. See standards §25.
# =============================================================================

import logging
import sqlite3

logger = logging.getLogger(__name__)


def _add_column_if_missing(c, table, col_name, col_type):
    """ALTER TABLE ADD COLUMN, swallowing the duplicate-column error."""
    try:
        c.execute(f"ALTER TABLE {table} ADD COLUMN {col_name} {col_type}")
    except sqlite3.OperationalError:
        pass


def apply(conn):
    c = conn.cursor()

    c.execute("""
        CREATE TABLE IF NOT EXISTS systems (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            folder TEXT NOT NULL UNIQUE,
            logo TEXT
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS games (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            system_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            publisher TEXT,
            developer TEXT,
            release_date TEXT,
            genre TEXT,
            rating TEXT,
            esrb_rating TEXT,
            pegi_rating TEXT,
            players INTEGER,
            modes TEXT,
            description TEXT,
            boxart TEXT,
            boxart_3d TEXT,
            screenshots TEXT,
            fanart TEXT,
            video TEXT,
            manual TEXT,
            region TEXT,
            franchise TEXT,
            similar_games TEXT,
            playtime_estimate TEXT,
            controller_support TEXT,
            save_type TEXT,
            sort_title TEXT,
            rom_path TEXT NOT NULL UNIQUE,
            scraped BOOLEAN DEFAULT 0,
            is_bonus_disc BOOLEAN DEFAULT 0,
            parent_game_id INTEGER,
            FOREIGN KEY(system_id) REFERENCES systems(id),
            FOREIGN KEY(parent_game_id) REFERENCES games(id)
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS publishers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            screenscraper_id TEXT UNIQUE,
            name TEXT NOT NULL
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS developers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            screenscraper_id TEXT UNIQUE,
            name TEXT NOT NULL
        )
    """)

    games_columns = [
        ('fanart', 'TEXT'),
        ('video', 'TEXT'),
        ('manual', 'TEXT'),
        ('region', 'TEXT'),
        ('franchise', 'TEXT'),
        ('similar_games', 'TEXT'),
        ('playtime_estimate', 'TEXT'),
        ('controller_support', 'TEXT'),
        ('save_type', 'TEXT'),
        ('scrape_history', 'TEXT'),
        ('completion_status', 'TEXT DEFAULT "not_started"'),
        ('file_size', 'INTEGER'),
        ('last_viewed', 'TEXT'),
        ('sort_title', 'TEXT'),
        ('hltb_match_name', 'TEXT'),
        ('hltb_match_platform', 'TEXT'),
        ('hltb_match_confidence', 'REAL'),
        ('boxart_3d', 'TEXT'),
        ('clz_title', 'TEXT'),
        ('perspective', 'TEXT'),
        ('dimension', 'TEXT'),
        ('created_at', 'TEXT'),
        ('last_bulk_scraped', 'TEXT'),
        ('steam_app_id', 'TEXT'),
        ('xbox_title_id', 'TEXT'),
        ('psn_npwr_id', 'TEXT'),
        ('cero_rating', 'TEXT'),
        ('usk_rating', 'TEXT'),
        ('acb_rating', 'TEXT'),
        ('fpb_rating', 'TEXT'),
        ('grac_rating', 'TEXT'),
        ('classind_rating', 'TEXT'),
        ('alternate_titles', 'TEXT'),
    ]
    for col_name, col_type in games_columns:
        _add_column_if_missing(c, 'games', col_name, col_type)

    # Backfill clz_title for existing CLZ imports (clz_title was added later;
    # rows imported before its existence have NULL).
    try:
        c.execute("""
            UPDATE games
            SET clz_title = SUBSTR(rom_path,
                LENGTH('clz_import/') + INSTR(SUBSTR(rom_path, LENGTH('clz_import/') + 1), '/') + 1)
            WHERE rom_path LIKE 'clz_import/%/%'
              AND (clz_title IS NULL OR clz_title = '')
        """)
        if c.rowcount > 0:
            logger.info("Backfilled clz_title for %d existing CLZ imports", c.rowcount)
    except Exception as e:
        logger.warning("Could not backfill clz_title: %s", e)

    c.execute("""
        CREATE TABLE IF NOT EXISTS game_achievement_progress (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            game_id INTEGER NOT NULL UNIQUE,
            ra_game_id INTEGER,
            earned_achievements INTEGER DEFAULT 0,
            total_achievements INTEGER DEFAULT 0,
            earned_points INTEGER DEFAULT 0,
            total_points INTEGER DEFAULT 0,
            completion_percentage REAL DEFAULT 0,
            last_synced TEXT,
            FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE
        )
    """)

    for col_name, col_type in [
        ('steam_app_id', 'TEXT'),
        ('xbox_title_id', 'TEXT'),
        ('source', "TEXT DEFAULT 'ra'"),
    ]:
        _add_column_if_missing(c, 'game_achievement_progress', col_name, col_type)

    c.execute("""
        CREATE TABLE IF NOT EXISTS normalization_rules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            category TEXT NOT NULL,
            from_value TEXT NOT NULL,
            to_value TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(category, from_value)
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS dropdown_options (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            category TEXT NOT NULL,
            value TEXT NOT NULL,
            sort_order INTEGER DEFAULT 0,
            UNIQUE(category, value)
        )
    """)

    perspective_defaults = [
        ('perspective', 'First-Person', 1),
        ('perspective', 'Isometric', 2),
        ('perspective', 'Side-Scroller', 3),
        ('perspective', 'Third-Person', 4),
        ('perspective', 'Top-Down', 5),
    ]
    for cat, val, order in perspective_defaults:
        c.execute(
            "INSERT OR IGNORE INTO dropdown_options (category, value, sort_order) VALUES (?, ?, ?)",
            (cat, val, order),
        )

    dimension_defaults = [
        ('dimension', '2D', 1),
        ('dimension', '2.5D', 2),
        ('dimension', '3D', 3),
        ('dimension', 'AR', 4),
        ('dimension', 'FMV', 5),
        ('dimension', 'Pseudo-3D', 6),
        ('dimension', 'VR', 7),
    ]
    for cat, val, order in dimension_defaults:
        c.execute(
            "INSERT OR IGNORE INTO dropdown_options (category, value, sort_order) VALUES (?, ?, ?)",
            (cat, val, order),
        )

    c.execute("CREATE INDEX IF NOT EXISTS idx_achievement_progress_game ON game_achievement_progress(game_id)")

    game_indexes = [
        ("idx_games_system_id", "system_id"),
        ("idx_games_is_bonus_disc", "is_bonus_disc"),
        ("idx_games_sort_title", "sort_title"),
        ("idx_games_parent_game_id", "parent_game_id"),
        ("idx_games_scraped", "scraped"),
        ("idx_games_title", "title"),
        ("idx_games_completion_status", "completion_status"),
        ("idx_games_has_retroachievements", "has_retroachievements"),
        ("idx_games_genre", "genre"),
        ("idx_games_developer", "developer"),
        ("idx_games_publisher", "publisher"),
        ("idx_games_franchise", "franchise"),
        ("idx_games_release_date", "release_date"),
        ("idx_games_critic_score", "critic_score"),
        ("idx_games_user_score", "user_score"),
        ("idx_games_file_size", "file_size"),
        ("idx_games_players", "players"),
        ("idx_games_created_at", "created_at"),
        ("idx_games_steam_app_id", "steam_app_id"),
        ("idx_games_xbox_title_id", "xbox_title_id"),
        ("idx_games_psn_npwr_id", "psn_npwr_id"),
        ("idx_games_rom_path", "rom_path"),
    ]
    for idx_name, idx_col in game_indexes:
        try:
            c.execute(f"CREATE INDEX IF NOT EXISTS {idx_name} ON games({idx_col})")
        except sqlite3.OperationalError:
            # Some indexes target columns added by other modules (e.g.
            # has_retroachievements / critic_score / user_score live in
            # ra_sync.py); skip silently if the column isn't there yet.
            pass

    composite_indexes = [
        ("idx_games_system_scraped", "system_id, scraped"),
        ("idx_games_system_bonus", "system_id, is_bonus_disc"),
        ("idx_games_system_bonus_scraped", "system_id, is_bonus_disc, scraped"),
    ]
    for idx_name, idx_cols in composite_indexes:
        try:
            c.execute(f"CREATE INDEX IF NOT EXISTS {idx_name} ON games({idx_cols})")
        except sqlite3.OperationalError:
            # Legacy install whose `games` table pre-dates one of the indexed
            # columns — the column will be re-added by the baseline's
            # games_columns ALTER block, but some composite indexes target
            # columns in the original CREATE TABLE (e.g. `scraped`). If a
            # minimal seeded DB is missing that column the index just gets
            # skipped; the normal startup path always has it.
            pass

    # PSN tables are created on first PSN sync (services/psn_sync.py); guard
    # ALTERs so a fresh install with no PSN data doesn't blow up.
    psn_games_exists = c.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='psn_games'"
    ).fetchone() is not None
    psn_sync_status_exists = c.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='psn_sync_status'"
    ).fetchone() is not None

    if psn_games_exists:
        _add_column_if_missing(c, 'psn_games', 'trophies_synced', 'INTEGER DEFAULT 0')

    if psn_sync_status_exists:
        for col_name, col_type in [("trophy_level", "INTEGER DEFAULT 0"), ("avatar_url", "TEXT")]:
            _add_column_if_missing(c, 'psn_sync_status', col_name, col_type)

    if psn_games_exists:
        for col_name, col_type in [
            ("hltb_id", "INTEGER"),
            ("hltb_title", "TEXT"),
            ("hltb_main", "TEXT"),
            ("hltb_extra", "TEXT"),
            ("hltb_complete", "TEXT"),
        ]:
            _add_column_if_missing(c, 'psn_games', col_name, col_type)

    c.execute("""
        CREATE TABLE IF NOT EXISTS job_queue (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            job_type TEXT NOT NULL,
            status TEXT DEFAULT 'running',
            progress TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            completed_at TEXT,
            error_message TEXT,
            params TEXT
        )
    """)

    c.execute("CREATE INDEX IF NOT EXISTS idx_job_queue_status ON job_queue(status)")

    c.execute("""
        CREATE TABLE IF NOT EXISTS tags (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL UNIQUE COLLATE NOCASE,
            color TEXT DEFAULT '#4cc9f0',
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS game_tags (
            game_id INTEGER NOT NULL,
            tag_id INTEGER NOT NULL,
            PRIMARY KEY (game_id, tag_id),
            FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
            FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS lists (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT,
            icon TEXT DEFAULT '📋',
            sort_order INTEGER DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS list_games (
            list_id INTEGER NOT NULL,
            game_id INTEGER NOT NULL,
            position INTEGER DEFAULT 0,
            added_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            PRIMARY KEY (list_id, game_id),
            FOREIGN KEY (list_id) REFERENCES lists(id) ON DELETE CASCADE,
            FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS wishlist (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            system_name TEXT,
            notes TEXT,
            priority INTEGER DEFAULT 2,
            added_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            game_id INTEGER,
            FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE SET NULL
        )
    """)

    wishlist_columns = [
        ('system_id', 'INTEGER'),
        ('boxart', 'TEXT'),
        ('boxart_3d', 'TEXT'),
        ('fanart', 'TEXT'),
        ('screenshots', 'TEXT'),
        ('video', 'TEXT'),
        ('manual', 'TEXT'),
        ('description', 'TEXT'),
        ('release_date', 'TEXT'),
        ('developer', 'TEXT'),
        ('publisher', 'TEXT'),
        ('genre', 'TEXT'),
        ('franchise', 'TEXT'),
        ('modes', 'TEXT'),
        ('players', 'INTEGER'),
        ('esrb_rating', 'TEXT'),
        ('pegi_rating', 'TEXT'),
        ('critic_score', 'REAL'),
        ('critic_score_count', 'INTEGER'),
        ('user_score', 'REAL'),
        ('user_score_count', 'INTEGER'),
        ('source', 'TEXT'),
        ('source_id', 'TEXT'),
        ('scrape_status', "TEXT DEFAULT 'unscraped'"),
        ('scraped_at', 'TEXT'),
    ]
    for col_name, col_type in wishlist_columns:
        _add_column_if_missing(c, 'wishlist', col_name, col_type)

    c.execute("CREATE INDEX IF NOT EXISTS idx_wishlist_scrape_status ON wishlist(scrape_status)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_wishlist_system_id ON wishlist(system_id)")

    c.execute("""
        CREATE TABLE IF NOT EXISTS hltb_pending_matches (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            game_id INTEGER NOT NULL UNIQUE,
            hltb_id INTEGER,
            match_name TEXT,
            match_platform TEXT,
            confidence REAL,
            playtime TEXT,
            main_story REAL,
            main_plus_sides REAL,
            completionist REAL,
            search_term_used TEXT,
            matched_via_alternate INTEGER DEFAULT 0,
            reason TEXT,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
            FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
        )
    """)
    c.execute("CREATE INDEX IF NOT EXISTS idx_hltb_pending_game_id ON hltb_pending_matches(game_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_hltb_pending_reason ON hltb_pending_matches(reason)")

    c.execute("""
        CREATE TABLE IF NOT EXISTS collector_trophies (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT,
            icon TEXT NOT NULL,
            tier TEXT NOT NULL DEFAULT 'bronze',
            category TEXT NOT NULL DEFAULT 'general',
            threshold INTEGER DEFAULT 0,
            earned_at TEXT,
            progress INTEGER DEFAULT 0
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS system_museum (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            system_id INTEGER NOT NULL UNIQUE,
            history TEXT,
            summary TEXT,
            top_games TEXT,
            generated_at TEXT,
            generated_by TEXT,
            FOREIGN KEY (system_id) REFERENCES systems(id) ON DELETE CASCADE
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS steam_achievements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            game_id INTEGER NOT NULL,
            apiname TEXT NOT NULL,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            icon_url TEXT,
            icon_locked_url TEXT,
            achieved INTEGER DEFAULT 0,
            unlock_time INTEGER DEFAULT 0,
            UNIQUE(game_id, apiname),
            FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
        )
    """)

    c.execute("""
        CREATE TABLE IF NOT EXISTS xbox_achievements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            game_id INTEGER NOT NULL,
            achievement_id TEXT NOT NULL,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            icon_url TEXT,
            icon_locked_url TEXT,
            gamerscore INTEGER DEFAULT 0,
            achieved INTEGER DEFAULT 0,
            unlock_time TEXT,
            UNIQUE(game_id, achievement_id),
            FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
        )
    """)

    c.execute("CREATE INDEX IF NOT EXISTS idx_game_tags_game ON game_tags(game_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_game_tags_tag ON game_tags(tag_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_list_games_list ON list_games(list_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_list_games_game ON list_games(game_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_wishlist_priority ON wishlist(priority)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_collector_trophies_tier ON collector_trophies(tier)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_system_museum_system ON system_museum(system_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_steam_ach_game ON steam_achievements(game_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_xbox_ach_game ON xbox_achievements(game_id)")
